let modelsJson = [
    {id:1, 
        name:'Calabresa', 
        tipo: 'Salgada',
        img:'imagens/mais-pedidas/calabresa.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, molho de tomate orgânico, calabresa defumada, cebola e queijo muçarela. '},
    {id:2, 
        name:'Francesa', 
        tipo: 'Vegetariana',
        img:'imagens/mais-pedidas/francesa.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, mix de shitake, shimeji, champignon, requeijão e tomate cereja.'},
    {id:3, 
        name:'Mineira', 
        tipo: 'Promoção',
        img:'imagens/mais-pedidas/mineira.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, muçarela, catupiry e milho verde.'},
    {id:4, 
        name:'Parma com rúcula', 
        tipo: 'Zero lactose',
        img:'imagens/mais-pedidas/parma-com-rucula.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, presunto Parma, folhas de rúcula, muçarela, orégano e tomates frescos.'},
    {id:5, 
        name:'batata-doce', 
        tipo: 'Vegana',
        img:'imagens/mais-pedidas/batata-doce.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira de batata-doce, quinoa, tomates em rodelas, folhas de manjericão e queijo vegano.'},
    {id:6, 
        name:'Banoffe', 
        tipo: 'Doce',
        img:'imagens/mais-pedidas/banoffe.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, doce de leite caseiro, banana, chantily fresco e canela indiana.'},
    {id:7, 
        name:'Pão de alho', 
        tipo: 'Salgada',
        img:'imagens/mais-pedidas/.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, creme de alho, requeijão, queijo muçarela e calabresa picante.'},
    {id:8, 
        name:'Italianissíma', 
        tipo: 'Salgada',
        img:'imagens/mais-pedidas/italianissima.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, recheio de alcachofra, muçarela de búfala e presunto parma.'},     
    
];