let modelsJson = [
    {id:1, 
        name:'Calabresa', 
        tipo: 'Salgada',
        img:'imagens/sabores-carrinho/calabresa.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, molho de tomate orgânico, calabresa defumada, cebola e queijo muçarela. '},
    {id:2, 
        name:'Camarão Cremosos', 
        tipo: 'Salgada',
        img:'imagens/sabores-carrinho/camarao-cremoso.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, molho de quatro queijos, camarão italiano, manjericão e queijo brie.'},
    {id:3, 
        name:'Portuguesa', 
        tipo: 'Salgada',
        img:'imagens/sabores-carrinho/portuguesa.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, tomates orgânicos, cebola roxa, azeitona, ovo picado, presunto e queijo muçarela.'},
    {id:4, 
        name:'Italianissima', 
        tipo: 'Salgada',
        img:'imagens/sabores-carrinho/italianissima.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, recheio de alcachofra, muçarela de búfala e presunto parma.'},
    {id:5, 
        name:'Tribeca', 
        tipo: 'Salgada',
        img:'imagens/sabores-carrinho/tribeca.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, cheddar, pepperoni, bacon e queijo crocante.'},
    {id:6, 
        name:'Caprese', 
        tipo: 'Salgada',
        img:'imagens/sabores-carrinho/caprese.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, muçarela tradicional, muçarela de búfala, rodelas de tomate, folhas de manjericão e pesto de azeitona.'},
    {id:7, 
        name:'Alcachofrinha', 
        tipo: 'Salgada',
        img:'imagens/sabores-carrinho/alcachofrinho.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, alcachofra, muçarela de búfala e azeitonas fatiadas.'},
    {id:8, 
        name:'Pão de alho', 
        tipo: 'Salgada',
        img:'imagens/sabores-carrinho/pao-de-alho.png', 
        price:[25.00, 35.00, 45.00], 
        sizes:['30cm', '40cm', '50cm'], 
        description:'Massa caseira, creme de alho, requeijão, queijo muçarela e calabresa picante.'},     
    
];